Update ir_table.py
change np.float to float to resolve error running ir_table:
Traceback (most recent call last):
  File "/mnt/scratch/splicedice/splicedice_env/bin/mesa", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/scratch/splicedice/splicedice_env/lib/python3.12/site-packages/mesa/__main__.py", line 59, in main
    args.main(args)
  File "/mnt/scratch/splicedice/splicedice_env/lib/python3.12/site-packages/mesa/ir_table.py", line 191, in run_with
    junctions, IR, RSD = calculateIR(samples,coverageDirectory,counts,clusters,annotated,args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/scratch/splicedice/splicedice_env/lib/python3.12/site-packages/mesa/ir_table.py", line 118, in calculateIR
    covArray = np.array(coverage[sample][cluster]).astype(np.float)
                                                          ^^^^^^^^
  File "/mnt/scratch/splicedice/splicedice_env/lib/python3.12/site-packages/numpy/__init__.py", line 394, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'float16'?